server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        # Define routes for each microservice
        # The 'lb://' prefix indicates that the service should be looked up via Eureka
        # USER-AUTH-SERVICE
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        # RESTAURANT-SERVICE
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/v1/restaurants/**
        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        # ORDER-SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        # DELIVERY-SERVICE
        - id: deliveries
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/api/v1/deliveries/**
        # NOTIFICATION-SERVICE
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
